using System;

namespace SecOpsSteward.Plugins
{
    /// <summary>
    ///     Attribute describing output keys generated by the Plugin
    /// </summary>
    [AttributeUsage(AttributeTargets.Class)]
    public class GeneratedSharedOutputsAttribute : Attribute
    {
        /// <summary>
        ///     Attribute describing output keys generated by the Plugin
        /// </summary>
        public GeneratedSharedOutputsAttribute(params string[] outputs)
        {
            GeneratedOutputs = outputs;
        }

        /// <summary>
        ///     Generated outputs from this Plugin
        /// </summary>
        public string[] GeneratedOutputs { get; }
    }

    /// <summary>
    ///     Attribute describing input keys required by the Plugin
    /// </summary>
    [AttributeUsage(AttributeTargets.Class)]
    public class RequiredSharedInputsAttribute : Attribute
    {
        /// <summary>
        ///     Attribute describing output keys generated by the Plugin
        /// </summary>
        public RequiredSharedInputsAttribute(params string[] inputs)
        {
            RequiredInputs = inputs;
        }

        /// <summary>
        ///     Required inputs for this Plugin
        /// </summary>
        public string[] RequiredInputs { get; }
    }
}