name: Build ARM Template
on:
  push:
    branches: [ main ]
    paths:
      - 'deploy/**'
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Bicep Build
        uses: aliencube/bicep-build-actions@v0.3
        with:
          files: 'deploy/*.bicep'
          
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: ./deploy/*
          message: 'Create ARM template from bicep'
          push: true
