name: Deploy Example

on:
  workflow_dispatch:

jobs:
  deploy:
    defaults:
      run:
        working-directory: ./src
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      # ----------
      
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          environment: azurecloud
          
      # ----------
          
      #- name: Setup .NET 3.1
      #  uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: 3.1.x
      #- name: Setup .NET 5
      #  uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: 5.0.x
          
      # ----------
          
      #- name: Restore dependencies
      #  run: dotnet restore
      #- name: Build
      #  run: dotnet build --no-restore
      #- name: Test
      #  run: dotnet test --no-build --verbosity normal
          
      # ----------
      
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          azPSVersion: latest
          inlineScript: |
            ${{ github.workspace }}\deploy\deploy.ps1 -Location westus -ResourceGroup sos-webapp-deploy -ApplicationSecret ${{ secrets.DEPLOY_SOS_APP_SECRET }} -WebAppName soswebapp -DeploymentId ghaction      
      
      # ----------
          
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az logout
            az cache purge
            az account clear
